### PR TITLE
Review

### PR DESCRIPTION
**Pull request by scheibel**
* Small code cleanup
* Use `cpplocate` to find run-time assets (no font-files though)
* Update source code to work with current master from glbinding and globjects (their releases are pending)
* Fix case-sensitive project name

### CODE REVIEW

**Comment by anne-gropler** [comment]
Thanks for this collab!

Can you try to fix the Travis built? It cannot find cpplocate.

`CMake Error at source/llassetgen-rendering/CMakeLists.txt:8 (find_package):
  By not providing "Findcpplocate.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "cpplocate", but CMake did not find one.
  Could not find a package configuration file provided by "cpplocate" with
  any of the following names:
    cpplocateConfig.cmake
    cpplocate-config.cmake
  Add the installation prefix of "cpplocate" to CMAKE_PREFIX_PATH or set
  "cpplocate_DIR" to a directory containing one of the above files.  If
  "cpplocate" provides a separate development package or SDK, be sure it has
  been installed.`

**Comment by scheibel** [comment]
I added the missing dependencies to both ubuntu and macOS configurations. However, the required glbinding and globjects versions are not yet deployed via PPA or Homebrew.

**Comment by scheibel** [comment]
Addendum: the glm package of Homebrew doesn't seem to install a `glm-config.cmake` file. We'll have to investigate this further.

**Comment by anne-gropler** [comment]
thank you! then for now, I feel I can approve this PR. Thank you for your work!

**Review by anne-gropler — APPROVED** [review]

**Pull request merged**
